[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sidg767", email = "dsidhrt7@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
]

[project.scripts]
ai = "ai:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
